### ISSUE TITLE
Heroku domain name

### ISSUE THREAD

**Issue by wu87988622** [JJSPython/parseltongue#1]
Heroku domain name 是可以自己取名的
看大家有沒有想法
我們可以先把名字搶起來
之後可以使用

@mathsigit @konekoya @jackyoh @LinTingYuan

**Comment by mathsigit** [comment]
Could you post the URL/image about setting domain name of Heroku?

**Comment by wu87988622** [comment]
https://dashboard.heroku.com/new-app

需要帳號~

**Comment by mathsigit** [comment]
> https://dashboard.heroku.com/new-app
需要帳號~

Do you mean as below?

![](https://files.gitter.im/JJSPython/Lobby/KS2z/Screen-Shot-2018-03-19-at-14.52.19.png)

**Comment by mathsigit** [comment]
@JJSPython/developer 
How about `jjspython-parseltongue`?
And the URL of the APP is https://jjspython-parseltongue.herokuapp.com/

**Comment by mathsigit** [comment]
Final result:
The URL of the APP is https://jjspython-parseltongue.herokuapp.com/.
Connecting to the https://github.com/JJSPython/parseltongue, and setting auto deploy.
