### ISSUE TITLE
UI discussion

### ISSUE THREAD

**Issue by konekoya** [JJSPython/parseltongue#2]
Some questions before I starting to work on the UIs:
1. How does user use our app? 
2. Does user able to download the scrape results?

And this is what I can come up with right now:
https://www.draw.io/#G1ZFn81V8DEvf5vljGCkKeMWJWdGIsCLOV

**Comment by mathsigit** [comment]
Thanks, @konekoya !

**Comment by konekoya** [comment]
Closing this, I'll open another issue in the parseltongue website repo
