### ISSUE TITLE
Update README.md to specify python version

### ISSUE THREAD

**Issue by konekoya** [JJSPython/parseltongue#6]

**Comment by konekoya** [comment]
@wu87988622 Could you help with this issue? I need to know the exact version of python in order to run it on my local machine.

**Comment by wu87988622** [comment]
Python version is with Heroku supported  version
now heroku specifying a Python version is python-3.6.6
if you want specify a Python version need add a runtime.txt
like this
  $cat runtime.txt
  python-x.x.x

**Comment by konekoya** [comment]
Thank you for the explanation! Is it possible that you can create a PR to add those details in the README.md of this Repo? I think I'll be able to work on this Project this week :)

**Comment by wu87988622** [comment]
OKOK
I create a PR 
Waiting for the @mathsigit  leader now

**Comment by konekoya** [comment]
#7 

@wu87988622 I'm linking the PR number here. This is the typical workflow when creating a new PR, you:

- Before creating a PR, open an issue to discuss or report a bug
- Open a PR and link the PR number in the related issue
- After the PR has merged, close the issue and delete the PR branch

Hope this help :)
